//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BrgyProfileCore.Properties {
    
    
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Editors.SettingsDesigner.SettingsSingleFileGenerator", "16.8.1.0")]
    internal sealed partial class Settings : global::System.Configuration.ApplicationSettingsBase {
        
        private static Settings defaultInstance = ((Settings)(global::System.Configuration.ApplicationSettingsBase.Synchronized(new Settings())));
        
        public static Settings Default {
            get {
                return defaultInstance;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Tanghawan")]
        public string BrgyName {
            get {
                return ((string)(this["BrgyName"]));
            }
            set {
                this["BrgyName"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Dingle")]
        public string Municipality {
            get {
                return ((string)(this["Municipality"]));
            }
            set {
                this["Municipality"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Iloilo")]
        public string Province {
            get {
                return ((string)(this["Province"]));
            }
            set {
                this["Province"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("John B. Smith")]
        public string RBI_PreparedBy {
            get {
                return ((string)(this["RBI_PreparedBy"]));
            }
            set {
                this["RBI_PreparedBy"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Erwin B. Smith")]
        public string RBI_CertifiedCorrected {
            get {
                return ((string)(this["RBI_CertifiedCorrected"]));
            }
            set {
                this["RBI_CertifiedCorrected"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Levi R. Ackerman")]
        public string RBI_ValidatedBy {
            get {
                return ((string)(this["RBI_ValidatedBy"]));
            }
            set {
                this["RBI_ValidatedBy"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("BHW")]
        public string RBI_PreparedByTitle {
            get {
                return ((string)(this["RBI_PreparedByTitle"]));
            }
            set {
                this["RBI_PreparedByTitle"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Brgy. Secretary")]
        public string RBI_CertifiedCorrectedTitle {
            get {
                return ((string)(this["RBI_CertifiedCorrectedTitle"]));
            }
            set {
                this["RBI_CertifiedCorrectedTitle"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Punong Barangay")]
        public string RBI_ValidatedByTitle {
            get {
                return ((string)(this["RBI_ValidatedByTitle"]));
            }
            set {
                this["RBI_ValidatedByTitle"] = value;
            }
        }
    }
}
