// <auto-generated />
using System;
using BrgyProfileCore;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace BrgyProfileCore.Migrations
{
    [DbContext(typeof(BrgyContext))]
    partial class BrgyContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "5.0.2");

            modelBuilder.Entity("BrgyProfileCore.Household", b =>
                {
                    b.Property<int>("HouseholdId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int?>("HeadResidentId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("HouseholdName")
                        .HasColumnType("TEXT");

                    b.HasKey("HouseholdId");

                    b.ToTable("Households");
                });

            modelBuilder.Entity("BrgyProfileCore.Resident", b =>
                {
                    b.Property<int>("ResidentId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Address")
                        .HasColumnType("TEXT");

                    b.Property<string>("ContactNumber")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("DateOfBirth")
                        .HasColumnType("TEXT");

                    b.Property<string>("FirstName")
                        .HasColumnType("TEXT");

                    b.Property<string>("Guardian")
                        .HasColumnType("TEXT");

                    b.Property<int?>("HouseholdId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("LastName")
                        .HasColumnType("TEXT");

                    b.Property<string>("MiddleName")
                        .HasColumnType("TEXT");

                    b.Property<int?>("SitioId")
                        .HasColumnType("INTEGER");

                    b.HasKey("ResidentId");

                    b.HasIndex("HouseholdId");

                    b.HasIndex("SitioId");

                    b.ToTable("Residents");
                });

            modelBuilder.Entity("BrgyProfileCore.Sitio", b =>
                {
                    b.Property<int>("SitioId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("SitioName")
                        .HasColumnType("TEXT");

                    b.HasKey("SitioId");

                    b.ToTable("Sitio");
                });

            modelBuilder.Entity("BrgyProfileCore.Resident", b =>
                {
                    b.HasOne("BrgyProfileCore.Household", "Household")
                        .WithMany("Residents")
                        .HasForeignKey("HouseholdId");

                    b.HasOne("BrgyProfileCore.Sitio", "Sitio")
                        .WithMany("Residents")
                        .HasForeignKey("SitioId");

                    b.Navigation("Household");

                    b.Navigation("Sitio");
                });

            modelBuilder.Entity("BrgyProfileCore.Household", b =>
                {
                    b.Navigation("Residents");
                });

            modelBuilder.Entity("BrgyProfileCore.Sitio", b =>
                {
                    b.Navigation("Residents");
                });
#pragma warning restore 612, 618
        }
    }
}
